//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Buyer : CardHolder
{
	public virtual string Name { get; set; }

	public virtual IEnumerable<PromProduct> PromProduct { get; set; }

    public virtual IEnumerable<ProdProduct> ProdProduct { get; set; }

    public virtual IEnumerable<Seller> Seller { get; set; }

    int CardHolder.Id
    {
        get { throw new NotImplementedException(); }

        set { throw new NotImplementedException(); }
    }

    public virtual void HasCard() { throw new NotImplementedException(); }

    public virtual void GetCardId() { throw new NotImplementedException(); }

    void CardHolder.HasCard() { throw new NotImplementedException(); }

    void CardHolder.GetCardId() { throw new NotImplementedException(); }
}

