//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public interface CardHolder 
{
	int Id { get;set; }

	void HasCard();

	void GetCardId();

}

