//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Card
{
	public virtual int Id { get; set; }

    public virtual string HolderName { get; set; }   

	public virtual Buyer Buyer { get; set; }
}

