//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class Product
{
	public virtual string Name { get; set; }

    public virtual int Price { get; set; }

    public virtual int Id { get; set; }

    public virtual object PriceCard { get; set; }

}

