//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Seller
{
	public virtual int Id { get; set; }

    public virtual string Name { get; set; }

    public virtual void SellProduct() { throw new NotImplementedException(); }

    public virtual void CreateCard() { throw new NotImplementedException(); }

}

